name: Clojure CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node dependencies
        uses: actions/setup-node@v2
        run: npm install

      - name: Build ClojureScript
        run: lein cljsbuild once min

      - name: Copy Files
        run: |
          mkdir ../out
          mkdir ../out/resources
          mkdir ../out/resources/public
          cp -r resources/public/* ../out/resources/public

      - name: Configure Git
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "Automation"

      - name: Commit Pages
        run: |
          git switch gh-pages
          rm -r *
          cp -r ../out/resources/public/* ./
          git add -u
          git add -v *
          git diff --staged --quiet && echo "No changes." || git commit -a -v -m "Build Pages" && git push -v
